'use client';
import "../build.css";
import "../globals.css";
import SidebarNavigation from "@/app/components/user/global/SidebarNavigation";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { SkeletonTheme } from "react-loading-skeleton";
import "react-loading-skeleton/dist/skeleton.css";
import { AppProgressBar } from "next-nprogress-bar";
// export const metadata = {
//   title: "matchmytees.com",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>MatchMyTees</title>
        <meta name="Description" content=""/>
        <link rel="stylesheet" href="../globals.css" />
        <link rel="stylesheet" href="../build.css" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="icon" href="../../images/favicon.jpg" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@600&amily=Roboto:wght@300;400;500&family=Abril+Fatface&family=Staatliches&display=swap" rel="stylesheet" />
      </head>
      <body className="">
        <SkeletonTheme baseColor="#D3D3D3" highlightColor="#B2BEB5">
          <ToastContainer
            position="top-right"
            autoClose={5000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="dark"
          />
          <div className="flex">
            <div className="">
              <SidebarNavigation />
            </div>
            <AppProgressBar height="4px" color="#ff5e01" />
            <div className="grow ">
              {children}
            </div>
            <div id="modal-container"></div>
          </div>
        </SkeletonTheme>
      </body>
    </html>
  );
}
